CREATE TABLE [dbo].[Entrega]
(  
    IdEntrega INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Entrega PRIMARY KEY CLUSTERED(IdEntrega)
  , FechaEntrega DATE NOT NULL 
  , Destino VARCHAR(250) NOT NULL
  , Camion VARCHAR(250) NOT NULL
  , Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION=PAGE)
GO
/*CREATE UNIQUE NONCLUSTERED INDEX IDX_Persona_Cedula
ON dbo.Persona(Cedula)
WITH (DATA_COMPRESSION=PAGE)
GO*/
