CREATE TABLE [dbo].[Camion]
(  
    IdCamion INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Camion PRIMARY KEY CLUSTERED(IdCamion)
  , Caracteristicas VARCHAR(250) NOT NULL
  , Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION=PAGE)
GO

CREATE UNIQUE NONCLUSTERED INDEX IDX_Camion_IdCamion
ON dbo.Camion(IdCamion)
WITH (DATA_COMPRESSION=PAGE)
GO
