CREATE TABLE [dbo].[Cliente]
(  
    IdCliente INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Persona PRIMARY KEY CLUSTERED(IdCliente)
  , Cedula VARCHAR(250) NOT NULL
  , NombreCompleto VARCHAR(250) NOT NULL
  , FechaNacimiento DATE NOT NULL 
  , Telefono INT NOT NULL
  , Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION=PAGE)
GO

CREATE UNIQUE NONCLUSTERED INDEX IDX_Cliente_Cedula
ON dbo.Cliente(Cedula)
WITH (DATA_COMPRESSION=PAGE)
GO